services:
  - type: web
    name: yfinance-backend
    env: python
    plan: free
    buildCommand: 'pip install -r requirements.txt'
    startCommand: 'python server.py'
    envVars:
      - key: PORT
        value: 3001
